### ISSUE TITLE
SuperDevMode throws Errors when using external library

### ISSUE THREAD

**Issue by confile** [Putnami/putnami-gradle-plugin#11]
I use the realtime-json library: https://github.com/goodow/realtime-json 

In my build.gradle I do: 

```
apply plugin: 'fr.putnami.gwt-lib'

buildscript {
  repositories {
    mavenCentral()
    jcenter()
    maven {
      url "https://oss.sonatype.org/content/repositories/snapshots/"
    }
  }
  dependencies {
    classpath 'fr.putnami.gwt:putnami-gradle-plugin:0.2.0-SNAPSHOT'
  }
}

dependencies {
  compile name: 'realtime-json-0.5.5-SNAPSHOT'
  compile name: 'realtime-json-0.5.5-SNAPSHOT-sources'
} 

repositories {
  flatDir {
    dirs 'lib'
  }
}

putnami {
  module 'test.mobile.mobilePhoneGapIOS'
  
  gwtVersion = "2.7.0"
  dev {
    bindAddress = "192.168.178.26"
    port = 9876
    precompile = true
    jsInteropMode = "JS"
    logLevel = "INFO"
  }
  
  
}

```

I can do ``gradle build``and it compiles without any errors. When I do ``gradle gwtCodeServer`` I get the following error: 

```
           [ERROR] An internal compiler exception occurred
com.google.gwt.dev.jjs.InternalCompilerException: Unexpected error during visit.
	at com.google.gwt.dev.jjs.ast.JVisitor.translateException(JVisitor.java:121)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:140)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:132)
	at com.google.gwt.dev.jjs.impl.Devirtualizer.getStaticImpl(Devirtualizer.java:561)
	at com.google.gwt.dev.jjs.impl.Devirtualizer.access$400(Devirtualizer.java:75)
	at com.google.gwt.dev.jjs.impl.Devirtualizer$RewriteVirtualDispatches.ensureDevirtualVersionExists(Devirtualizer.java:184)
	at com.google.gwt.dev.jjs.impl.Devirtualizer$RewriteVirtualDispatches.endVisit(Devirtualizer.java:101)
	at com.google.gwt.dev.jjs.ast.JMethod.traverse(JMethod.java:571)
	at com.google.gwt.dev.jjs.ast.JModVisitor$ListContextImmutable.traverse(JModVisitor.java:183)
	at com.google.gwt.dev.jjs.ast.JModVisitor.acceptWithInsertRemoveImmutable(JModVisitor.java:356)
	at com.google.gwt.dev.jjs.ast.JInterfaceType.traverse(JInterfaceType.java:75)
	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:381)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:293)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:285)
	at com.google.gwt.dev.jjs.ast.JProgram.visitModuleTypes(JProgram.java:1191)
	at com.google.gwt.dev.jjs.ast.JProgram.traverse(JProgram.java:1155)
	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:381)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:293)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:285)
	at com.google.gwt.dev.jjs.impl.Devirtualizer.execImpl(Devirtualizer.java:319)
	at com.google.gwt.dev.jjs.impl.Devirtualizer.exec(Devirtualizer.java:218)
	at com.google.gwt.dev.jjs.MonolithicJavaToJavaScriptCompiler$MonolithicPermutationCompiler.normalizeSemantics(MonolithicJavaToJavaScriptCompiler.java:95)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler$PermutationCompiler.compilePermutation(JavaToJavaScriptCompiler.java:285)
	at com.google.gwt.dev.jjs.MonolithicJavaToJavaScriptCompiler.compilePermutation(MonolithicJavaToJavaScriptCompiler.java:296)
	at com.google.gwt.dev.jjs.UnifiedAst.compilePermutation(UnifiedAst.java:143)
	at com.google.gwt.dev.CompilePerms.compile(CompilePerms.java:197)
	at com.google.gwt.dev.ThreadedPermutationWorkerFactory$ThreadedPermutationWorker.compile(ThreadedPermutationWorkerFactory.java:50)
	at com.google.gwt.dev.PermutationWorkerFactory$Manager$WorkerThread.run(PermutationWorkerFactory.java:74)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:137)
	... 27 more
               [ERROR] <no source info>: <source info not available>
               [ERROR] at JsonElement.java(19): public abstract JsonElement clear();

                  com.google.gwt.dev.jjs.ast.JMethod
               [ERROR] at JsonElement.java(18): interface JsonElement extends Serializable 
                  com.google.gwt.dev.jjs.ast.JInterfaceType
               [ERROR] at Unknown(0): <JProgram>
                  com.google.gwt.dev.jjs.ast.JProgram
            [ERROR] Unrecoverable exception, shutting down
com.google.gwt.core.ext.UnableToCompleteException: (see previous log entries)
	at com.google.gwt.dev.javac.CompilationProblemReporter.logAndTranslateException(CompilationProblemReporter.java:106)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler$PermutationCompiler.compilePermutation(JavaToJavaScriptCompiler.java:363)
	at com.google.gwt.dev.jjs.MonolithicJavaToJavaScriptCompiler.compilePermutation(MonolithicJavaToJavaScriptCompiler.java:296)
	at com.google.gwt.dev.jjs.UnifiedAst.compilePermutation(UnifiedAst.java:143)
	at com.google.gwt.dev.CompilePerms.compile(CompilePerms.java:197)
	at com.google.gwt.dev.ThreadedPermutationWorkerFactory$ThreadedPermutationWorker.compile(ThreadedPermutationWorkerFactory.java:50)
	at com.google.gwt.dev.PermutationWorkerFactory$Manager$WorkerThread.run(PermutationWorkerFactory.java:74)
	at java.lang.Thread.run(Thread.java:745)
            [ERROR] Not all permutation were compiled , completed (0/1)
      [WARN] recompile failed
      [WARN] continuing to serve previous version
```

**Comment by fdumay** [comment]
@confile I think that issue is  solved.
Right now, I published the SNAPSHOT, 
If you assert that it works for you, I will push it.

**Comment by confile** [comment]
okay let me test it

**Comment by confile** [comment]
@fdumay No it does not work. I got the same error.

**Comment by confile** [comment]
@fdumay I tested it twice with different projects still gives the same error.

**Comment by fdumay** [comment]
@confile I used the runtimeClasspath instead of compileClasspath. I published a new SNAPSHOT.
Can you retry with --refresh-dependencies

I'am sorry to make you work so hard, but I'm feeling blind because I do not reproduce it

**Comment by confile** [comment]
@fdumay No problem I am happy to help you with the plugin. You did a great job. It solved a lot of problems I had with the other GWT plugin.  I am very thankful for that. 

I tried you latest changed but now it gets worse. When ``gradle build``leads to no error the ``gradle gwtCodeServer`` produces the following error: 

```
Super Dev Mode starting up
   workDir: /Users/mg/Documents/Grails/GGTS3.6.3-SR1/test-gwt/build/putnami/work
   Loading inherited module 'test.mobile.mobilePhoneGapIOS'
      Loading inherited module 'com.google.code.gwt.database.Html5Database'
         [ERROR] Line 31: Unable to load class 'com.google.code.gwt.database.rebind.DataServiceGenerator'
java.lang.ClassNotFoundException: com.google.code.gwt.database.rebind.DataServiceGenerator
```

I since build went without problems it seems that the Generator is not started for some reason.

**Comment by confile** [comment]
Just to be clear I used this snapshot: putnami-gradle-plugin-0.2.0-20150219.160830-8.jar

**Comment by confile** [comment]
@fdumay I created a simple demo project for you to save you some time. Here is it: https://github.com/confile/putnami-gradle-demo

I hope this helps. May be it was not your problem. If I can help you in any way please let me know.

**Comment by fdumay** [comment]
Okay I go ahead! I burned a lot gaz to resolve dependencies and build the test-core.
Thank to have made this project, without, I wouldn't be able to do anything. (okay nothing is done yet, but still hope)

Now I think that I've got the clear mind.

* The transitive seem to disturb the process, why do you need it?
* The ATP plugin generates some sources which are not included into artifact. We need to add test-core/build.gradle
``` 
jar {
   from "build/source/apt"		
}
```
* gwtRun seems okay
* but the gwtDev is still down. with the same issue : 
```
Caused by: java.lang.NullPointerException
    at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:137)
    ... 27 more
```

I will not be so much available till monday, so if you hit anything, let me know.

**Comment by branflake2267** [comment]
I haven't been following to close, but library order may be an option.

**Comment by confile** [comment]
@branflake2267 Which order do you suggest?

**Comment by branflake2267** [comment]
Be sure GWT libs are first, so they clobber any other libraries come into play. I suspect his is already in play but I mention it anyway.

**Comment by confile** [comment]
@branflake2267 So you mean the order in the dependencies block? That we should include the GWT lib first there?

**Comment by confile** [comment]
@fdumay Okay I let you know what I found. I use

```
  compile(project(':test-core')) {
    transitive = false
  }
```
because without it I have to include all the dependencies from ``test-core`` in my ``test-gwt`` project. This seems to be a little bit redundant. If I want to use the test-core project for other Java projects which are not GWT then there might be libraries included which are not available in GWT. I want that the test-gwt project only includes the libs which are relevant for GWT.

**Comment by confile** [comment]
@fdumay I tried to run only the code server but still I get: 

```
GET /recompile/gwtt
   Job test.gwtt_1_0
      starting job: test.gwtt_1_0
      Compiling module test.gwtt
         Unification traversed 6750 fields and methods and 573 types. 563 are considered part of the current module and 563 had all of their fields and methods traversed.
         Compiling 1 permutation
            Compiling permutation 0...
            [ERROR] An internal compiler exception occurred
com.google.gwt.dev.jjs.InternalCompilerException: Unexpected error during visit.
	at com.google.gwt.dev.jjs.ast.JVisitor.translateException(JVisitor.java:121)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:140)
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:132)
	at com.google.gwt.dev.jjs.impl.Devirtualizer.getStaticImpl(Devirtualizer.java:561)
	at com.google.gwt.dev.jjs.impl.Devirtualizer.access$400(Devirtualizer.java:75)
	at com.google.gwt.dev.jjs.impl.Devirtualizer$RewriteVirtualDispatches.ensureDevirtualVersionExists(Devirtualizer.java:184)
	at com.google.gwt.dev.jjs.impl.Devirtualizer$RewriteVirtualDispatches.endVisit(Devirtualizer.java:101)
	at com.google.gwt.dev.jjs.ast.JMethod.traverse(JMethod.java:571)
	at com.google.gwt.dev.jjs.ast.JModVisitor$ListContextImmutable.traverse(JModVisitor.java:183)
	at com.google.gwt.dev.jjs.ast.JModVisitor.acceptWithInsertRemoveImmutable(JModVisitor.java:356)
	at com.google.gwt.dev.jjs.ast.JInterfaceType.traverse(JInterfaceType.java:75)
	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:381)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:293)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:285)
	at com.google.gwt.dev.jjs.ast.JProgram.visitModuleTypes(JProgram.java:1191)
	at com.google.gwt.dev.jjs.ast.JProgram.traverse(JProgram.java:1155)
	at com.google.gwt.dev.jjs.ast.JModVisitor.traverse(JModVisitor.java:381)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:293)
	at com.google.gwt.dev.jjs.ast.JModVisitor.accept(JModVisitor.java:285)
	at com.google.gwt.dev.jjs.impl.Devirtualizer.execImpl(Devirtualizer.java:319)
	at com.google.gwt.dev.jjs.impl.Devirtualizer.exec(Devirtualizer.java:218)
	at com.google.gwt.dev.jjs.MonolithicJavaToJavaScriptCompiler$MonolithicPermutationCompiler.normalizeSemantics(MonolithicJavaToJavaScriptCompiler.java:95)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler$PermutationCompiler.compilePermutation(JavaToJavaScriptCompiler.java:285)
	at com.google.gwt.dev.jjs.MonolithicJavaToJavaScriptCompiler.compilePermutation(MonolithicJavaToJavaScriptCompiler.java:296)
	at com.google.gwt.dev.jjs.UnifiedAst.compilePermutation(UnifiedAst.java:143)
	at com.google.gwt.dev.CompilePerms.compile(CompilePerms.java:197)
	at com.google.gwt.dev.ThreadedPermutationWorkerFactory$ThreadedPermutationWorker.compile(ThreadedPermutationWorkerFactory.java:50)
	at com.google.gwt.dev.PermutationWorkerFactory$Manager$WorkerThread.run(PermutationWorkerFactory.java:74)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.google.gwt.dev.jjs.ast.JVisitor.accept(JVisitor.java:137)
	... 27 more
               [ERROR] <no source info>: <source info not available>
               [ERROR] at JsonElement.java(19): public abstract JsonElement clear();

                  com.google.gwt.dev.jjs.ast.JMethod
               [ERROR] at JsonElement.java(18): interface JsonElement extends Serializable 
                  com.google.gwt.dev.jjs.ast.JInterfaceType
               [ERROR] at Unknown(0): <JProgram>
                  com.google.gwt.dev.jjs.ast.JProgram
            [ERROR] Unrecoverable exception, shutting down
com.google.gwt.core.ext.UnableToCompleteException: (see previous log entries)
	at com.google.gwt.dev.javac.CompilationProblemReporter.logAndTranslateException(CompilationProblemReporter.java:106)
	at com.google.gwt.dev.jjs.JavaToJavaScriptCompiler$PermutationCompiler.compilePermutation(JavaToJavaScriptCompiler.java:363)
	at com.google.gwt.dev.jjs.MonolithicJavaToJavaScriptCompiler.compilePermutation(MonolithicJavaToJavaScriptCompiler.java:296)
	at com.google.gwt.dev.jjs.UnifiedAst.compilePermutation(UnifiedAst.java:143)
	at com.google.gwt.dev.CompilePerms.compile(CompilePerms.java:197)
	at com.google.gwt.dev.ThreadedPermutationWorkerFactory$ThreadedPermutationWorker.compile(ThreadedPermutationWorkerFactory.java:50)
	at com.google.gwt.dev.PermutationWorkerFactory$Manager$WorkerThread.run(PermutationWorkerFactory.java:74)
	at java.lang.Thread.run(Thread.java:745)
            [ERROR] Not all permutation were compiled , completed (0/1)
      [WARN] recompile failed
      [WARN] continuing to serve previous version
```

**Comment by fdumay** [comment]
Hi @branflake2267, I agree that the classpath order does matter, but I'am not fan to put GWT's deps first in the classpath. It would prevent user (or third libs) to override some GWT classes. In the case that the user realy want those libs first, he can add an explicitly on his dependency section in the build.gradle

**Comment by fdumay** [comment]
@confile I've got it :D 

you must set `dev{ incrmental = false }` . I don't know why but otherwise realtime-jason doesnn't work.
I'll make a PR on your demo project.

**Comment by confile** [comment]
@fdumay Well that is good, but the problem is that incremental compile must be true. Otherwise I have to wait to long for the project to compile. Lets close this issue because it does not belong to your project anymore. Thank you for your help. I think I will keep Dagger and Skip the crappy JSON lib :-)

**Comment by branflake2267** [comment]
Sounds like a generator is not extending incremental generator, or the resource interface needs to be updated. Update the interface with a space so the file gets a new update time.

**Comment by confile** [comment]
@branflake2267 There are no Generators in the lib.

**Comment by confile** [comment]
@branflake2267 resource interface is not used in the JSON lib.

**Comment by branflake2267** [comment]
Gotcha, I'm not aware of all the context, not enough time to dig in. I just know from other issues I've seen. I'm just throwing stuff against the wall to see if something might stick. I know from other issues, incremental won't update. Just out of curiosity, would this work with a generic java code server entry point launcher with -launcherDir path/To/OutputWar and gwtModule for the args? I'm not familiar enough with all the working parts, and probably not enough time yet to do dig in more.

**Comment by fdumay** [comment]
@confile yes you'd better drop that realtime-json! adding to i don't really understand the real value of this lib.

**Comment by confile** [comment]
@fdumay The value is that you have cross platform JSON lib. 

It seems that their latest push fixed the problem. So I close this issue.
