### ISSUE TITLE
Generators are not found in SuperDevMode

### ISSUE THREAD

**Issue by confile** [Putnami/putnami-gradle-plugin#18]
It looks like some Generators are not found in SuperDevMode. I created a sample project for this here: 

https://github.com/confile/putnami-gradle-demo

When doing ``gradle build``everything works fine but running the code server only gives the following errors:

```
Super Dev Mode starting up
   workDir: /Users/mg/Documents/Grails/GGTS3.6.3-SR1-2/buddyis-gwt/build/putnami/work
   Loading inherited module 'buddyis.mobile.mobilePhoneGapIOS'
      Loading inherited module 'com.google.code.gwt.database.Html5Database'
         [ERROR] Line 31: Unable to load class 'com.google.code.gwt.database.rebind.DataServiceGenerator'
java.lang.ClassNotFoundException: com.google.code.gwt.database.rebind.DataServiceGenerator
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at com.google.gwt.dev.cfg.ModuleDefSchema$ClassAttrCvt.convertToArg(ModuleDefSchema.java:902)
	at com.google.gwt.dev.util.xml.HandlerArgs.convertToArg(HandlerArgs.java:64)
	at com.google.gwt.dev.util.xml.HandlerMethod.invokeBegin(HandlerMethod.java:221)
	at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.startElement(ReflectiveParser.java:296)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.parse(ReflectiveParser.java:349)
	at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.access$200(ReflectiveParser.java:70)
	at com.google.gwt.dev.util.xml.ReflectiveParser.parse(ReflectiveParser.java:431)
	at com.google.gwt.dev.cfg.ModuleDefLoader.nestedLoad(ModuleDefLoader.java:377)
	at com.google.gwt.dev.cfg.ModuleDefSchema$BodySchema.__inherits_begin(ModuleDefSchema.java:504)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.google.gwt.dev.util.xml.HandlerMethod.invokeBegin(HandlerMethod.java:230)
	at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.startElement(ReflectiveParser.java:296)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at org.apache.xerces.impl.dtd.XMLDTDValidator.emptyElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.parse(ReflectiveParser.java:349)
	at com.google.gwt.dev.util.xml.ReflectiveParser$Impl.access$200(ReflectiveParser.java:70)
	at com.google.gwt.dev.util.xml.ReflectiveParser.parse(ReflectiveParser.java:431)
	at com.google.gwt.dev.cfg.ModuleDefLoader.nestedLoad(ModuleDefLoader.java:377)
	at com.google.gwt.dev.cfg.ModuleDefLoader.load(ModuleDefLoader.java:290)
	at com.google.gwt.dev.cfg.ModuleDefLoader.doLoadModule(ModuleDefLoader.java:229)
	at com.google.gwt.dev.cfg.ModuleDefLoader.loadFromResources(ModuleDefLoader.java:167)

	at com.google.gwt.dev.codeserver.Recompiler.loadModule(Recompiler.java:438)
BUILD SUCCESSFUL
	at com.google.gwt.dev.codeserver.Recompiler.initWithoutPrecompile(Recompiler.java:190)

	at com.google.gwt.dev.codeserver.Outbox.maybePrecompile(Outbox.java:82)
Total time: 2.379 secs
	at com.google.gwt.dev.codeserver.Outbox.<init>(Outbox.java:61)
	at com.google.gwt.dev.codeserver.CodeServer.makeOutboxes(CodeServer.java:156)
	at com.google.gwt.dev.codeserver.CodeServer.start(CodeServer.java:118)
	at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:91)
	at com.google.gwt.dev.codeserver.CodeServer.main(CodeServer.java:50)
```

**Comment by confile** [comment]
The source works perfect if I use it in a web application project from the eclipse GW plugin. Even super dev mode works without any problems.

**Comment by confile** [comment]
@fdumay if I can help you find this bug somehow let me know.

**Comment by fdumay** [comment]
Sorry for the delay, I wasn't connected the WE.
The sources and outputs of the project wasn't include to the CodeServer classpath.

**Comment by fdumay** [comment]
Should be fix with the lastest SNAPSHOT

**Comment by confile** [comment]
@fdumay Thank you very much it works great now. This plugin is so awesome. You did a great job.
