### ISSUE TITLE
Eclipse JSNI Support in Putnami Gradle

### ISSUE THREAD

**Issue by confile** [Putnami/putnami-gradle-plugin#35]
When running GWT in Eclipse as Web Application project I have a much better Assistent than using your plugin. This is for example in JSNI. I miss code completion there. Is there something I can configure to get code completion also with your grade plugin using in Eclipse?

**Comment by fdumay** [comment]
duplicate with #21

**Comment by fdumay** [comment]
Hi @confile, I added the google plugin eclipse nature.

to enable it you must have:

```
apply plugin: 'eclipse'
...
putnami{
	...
	googlePluginEclipse = true
}
```

let me know if it solve the issue.

**Comment by confile** [comment]
I test it as soon as possible and give you feedback. Can you please submit a new snapshot version or explain how I remove an old local build from cradle cache?

**Comment by fdumay** [comment]
Ok thanks.
The 0.3.0-SNAPSHOT is already published. You can refresh the cache `gradle build --refresh-dependencies`

**Comment by confile** [comment]
I tried this. Now I get the following error when I do build: 

```
:gwtCompile
Compiling module majestella.dashboard.MajestellaDashboard
[ERROR] Unexpected internal compiler error
java.lang.IncompatibleClassChangeError: class com.google.gwt.dev.javac.BytecodeSignatureMaker$CompileDependencyVisitor has interface org.objectweb.asm.ClassVisitor as super class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.google.gwt.dev.javac.BytecodeSignatureMaker.visitCompileDependenciesInBytecode(BytecodeSignatureMaker.java:227)
	at com.google.gwt.dev.javac.BytecodeSignatureMaker.getCompileDependencySignature(BytecodeSignatureMaker.java:209)
	at com.google.gwt.dev.javac.CompiledClass.getSignatureHash(CompiledClass.java:165)
	at com.google.gwt.dev.javac.Dependencies$Ref.<init>(Dependencies.java:41)
	at com.google.gwt.dev.javac.Dependencies$Ref.<init>(Dependencies.java:36)
	at com.google.gwt.dev.javac.Dependencies.resolve(Dependencies.java:100)
	at com.google.gwt.dev.javac.CompilationStateBuilder$CompileMoreLater.compile(CompilationStateBuilder.java:352)
	at com.google.gwt.dev.javac.CompilationStateBuilder.doBuildFrom(CompilationStateBuilder.java:548)
	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:479)
	at com.google.gwt.dev.javac.CompilationStateBuilder.buildFrom(CompilationStateBuilder.java:465)
	at com.google.gwt.dev.cfg.ModuleDef.getCompilationState(ModuleDef.java:423)
	at com.google.gwt.dev.Precompile.precompile(Precompile.java:222)
	at com.google.gwt.dev.Precompile.precompile(Precompile.java:202)
	at com.google.gwt.dev.Precompile.precompile(Precompile.java:143)
	at com.google.gwt.dev.Compiler.run(Compiler.java:197)
	at com.google.gwt.dev.Compiler.run(Compiler.java:156)
	at com.google.gwt.dev.Compiler$1.run(Compiler.java:117)
	at com.google.gwt.dev.CompileTaskRunner.doRun(CompileTaskRunner.java:55)
	at com.google.gwt.dev.CompileTaskRunner.runWithAppropriateLogger(CompileTaskRunner.java:50)
	at com.google.gwt.dev.Compiler.main(Compiler.java:124)
:gwtCompile FAILED
```

Do you have any idea how to solve this?

**Comment by fdumay** [comment]
I do not meet this issue... 
It should be a lib conflict, but i'm necked for solving it.
Can you provide more details? some thing like your build.gradle, or the `gradle dependencies'.

**Comment by confile** [comment]
Where does you plugin prints the compilation errors?

Here is my build.gradle: 

```
apply plugin: 'java'
apply plugin: 'fr.putnami.gwt'
apply plugin: 'war'
apply plugin: 'eclipse'

sourceCompatibility = 1.8
version = '1.0'
group = 'majestella.gwt'


buildscript {
  repositories {
    mavenCentral()
    jcenter()
    maven {
      url "https://oss.sonatype.org/content/repositories/snapshots/"
    }
    maven {
      url uri('../../0Gradle-Repo')
    }
//    maven {
//      url "https://oss.sonatype.org/content/repositories/vaadin-snapshots/"
//    }
//    maven {
//      url "https://oss.sonatype.org/content/repositories/google-snapshots/"
//    }
  }
  dependencies {
//    classpath 'fr.putnami.gwt:putnami-gradle-plugin:0.2.0'
    classpath 'fr.putnami.gwt:putnami-gradle-plugin:0.3.0-SNAPSHOT'
  }
}


repositories {
  mavenCentral()
  maven {
    name = "sonatype"
    url = "https://oss.sonatype.org/content/repositories/snapshots/"
  }
  maven {
    name = "sonatypeGoogle"
    url = "https://oss.sonatype.org/content/repositories/google-snapshots/"
  }
  maven {
    name = "VaadinSnapshots"
    url "https://oss.sonatype.org/content/repositories/vaadin-snapshots/"
  }
  flatDir {
    dirs 'lib'
  }
}


// required for GWT validation 
configurations.all {
  resolutionStrategy {
      force 'org.hibernate:hibernate-validator:4.1.0.Final'
      force 'org.hibernate:hibernate-validator:4.1.0.Final:sources'
      force 'com.fasterxml.jackson.core:jackson-annotations:2.3.0'
      force 'com.fasterxml.jackson.core:jackson-annotations:2.3.0:sources'
      
//      force 'com.google.guava:guava-gwt:20.0-SNAPSHOT-20160125.165735-51'
  }
}

dependencies {
//  compile(project(':buddyis-core'))
//  compile(project(':buddyis-core-emul'))
  

//  compile 'com.google.guava:guava-gwt:19.0'  // GWT 2.7
  compile 'com.google.guava:guava-gwt:20.0-SNAPSHOT'  // GWT 2.8 
//  compile group: "com.google.guava", name: "guava-gwt", version: "20.0-SNAPSHOT", changing: false
  
  
  compile 'javax.inject:javax.inject:1' 
  
//  compile 'com.gwtplatform:gwtp-all:1.4'
  compile 'com.gwtplatform:gwtp-all:1.5.1'
  compile 'com.github.nmorel.gwtjackson:gwt-jackson:0.11.1'
  
  compile 'javax.inject:javax.inject:1'
  compile 'javax.inject:javax.inject:1:sources'
  compile 'org.hibernate:hibernate-validator:4.1.0.Final'
  compile 'org.hibernate:hibernate-validator:4.1.0.Final:sources'
  compile 'com.fasterxml.jackson.core:jackson-annotations:2.3.0'
  compile 'com.fasterxml.jackson.core:jackson-annotations:2.3.0:sources'
  compile 'junit:junit:4.11'
  compile 'com.googlecode.objectify:objectify:4.0'
  compile 'org.slf4j:slf4j-api:1.7.10'
  compile 'org.slf4j:slf4j-simple:1.7.10'
  
//  compile 'com.googlecode.gwtquery:gwtquery:1.4.3'    
  compile 'com.googlecode.gwt-streamer:gwt-streamer:2.0.0'
  compile 'org.vectomatic:lib-gwt-file:0.3.6'
//  compile 'com.vaadin.polymer:vaadin-gwt-polymer-elements:1.2.3.0'  // GWT 2.8
//  compile 'com.vaadin.polymer:vaadin-gwt-polymer-elements:1.1.3.0-alpha1' // GWT 2.7
  compile 'com.vaadin.polymer:vaadin-gwt-polymer-elements:1.2.3.1-SNAPSHOT'  // GWT 2.8
  
//  compile 'org.atmosphere.extensions:atmosphere-gwt20-client:2.4.1'
//  compile 'org.atmosphere.extensions:atmosphere-gwt20-common:2.4.1'
  
//  compile 'com.googlecode.gwtquery:gwtquery:1.5-beta1'
  
  // using this https://github.com/Atmosphere/atmosphere-extensions/issues/194 for GWT 2.7
  compile name: 'atmosphere-gwt20-client-2.4.2-SNAPSHOT'
  compile name: 'atmosphere-gwt20-common-2.4.2-SNAPSHOT'
  
  compile name: 'gwtquery-1.4.4-SNAPSHOT'
  compile name: 'gwt-log-3.3.2'
  
  compile name: 'mgwt-2.0.1-SNAPSHOT'
  
  
//  compile name: 'gwt-pushstate-2.0.0'
//  compile name: 'gwt-reltime-0.90-b10'
  

//  compile name: 'fr.hd3d.html5.video.1.0'
//  compile name: 'gestures-plugin-1.0-SNAPSHOT'
  compile name: 'gwt-image-loader-1.1.4'
//  compile name: 'gwt-pushstate-2.0.0'
//  compile name: 'GWT-Relative-Time-1.0-SNAPSHOT'
//  compile name: 'gwt-streamer-1.0.1'
//  compile name: 'gwtquery-1.4.3-20141231.143602-16'
//  compile name: 'lib-gwt-file-0.3.5'
//  compile name: 'lib-gwt-svg-0.5.10-SNAPSHOT'
  
  
//  compile 'com.google.code.findbugs:jsr305:3.0.1'
//  compile 'com.google.errorprone:error_prone_annotations:2.0.8'
//  compile 'com.google.j2objc:j2objc-annotations:0.9.8'
//  compile 'com.google.guava:guava-testlib:19.0'
//  compile 'com.google.guava:guava-tests:19.0'
//  compile 'com.google.truth:truth:0.28'
//  
//  
//  
//  compile name: 'guava-gwt-20.0-20160125.165735-51'
//  compile name: 'guava-20.0-20160125.165523-51'
  
  
}


// Bugfix for Guava-20-SNAPSHOT
// https://discuss.gradle.org/t/compilation-fails-when-i-use-guavas-optional-class-duplicate-class-com-google-common-collect-abstractiterator/7370
tasks.withType(JavaCompile) {
  options.compilerArgs += ["-sourcepath", ""]
}


task copyLibWebComponents(type: Copy) {
  description "Copy webcomponents js files to magesstella main project"
  from buildDir.toString() + "/putnami/out/majestella_dashboard/bower_components"
  into "../majestella/grails-app/assets/javascripts/polymer"
}
tasks.build.finalizedBy copyLibWebComponents

task copyDashboardSybolMaps(type: Copy) {
  description "Copy SymbolMaps files to magesstella project"
  from buildDir.toString() + "/putnami/extra/majestella_dashboard/symbolMaps"
  into "../majestella/web-app/WEB-INF/dashboard/symbolMaps"
}
tasks.build.finalizedBy copyDashboardSybolMaps

//task copyLibDashboard(type: Copy) {
//  description "Copy the compiled files for the dashboard to magesstella main project"
//  from buildDir.toString() + "/putnami/out/majestella_dashboard"
//  into "../majestella/grails-app/assets/javascripts/dashboard"
//}
//tasks.build.finalizedBy copyLibDashboard

//task copyLibClientWidget(type: Copy) {
//  description "Copy the compiled files for the chat widget to magesstella main project"
//  from buildDir.toString() + "/putnami/out/majestella_client_chat"
//  into "../majestella/grails-app/assets/javascripts/clientwidget"
//}
//tasks.build.finalizedBy copyLibClientWidget

putnami {
//  module 'majestella.widget.MajestellaClientChat', 'majestella.dashboard.MajestellaDashboard'
  module 'majestella.dashboard.MajestellaDashboard'
//  module 'majestella.widget.MajestellaClientChat'
  
  // add gwt nature on eclipse projec. require apply plugin: 'eclipse' to work. default : false
  googlePluginEclipse = true
  
//  gwtVersion='2.7.0'
  gwtVersion='2.8.0-SNAPSHOT'
//  gwtVersion='2.8.0-beta1'  //  has bug wait for beta2
  compile {
    strict = true
//    jsInteropMode = "JS"  // jsInterpMode=JS_RC // GWT 2.8
    generateJsInteropExports = true  // GWT 2.8
    logLevel = "INFO"    
    
    /** Java args */
    maxHeapSize="1024m"
  }
  
  dev {
    strict = true
    noServer = true
//    bindAddress = "192.168.178.26"  // WLAN
    bindAddress = "192.168.178.28"    // LAN
//    bindAddress = "localhost"
    port = 9876
    precompile = true
//    jsInteropMode = "JS"
    generateJsInteropExports = true // GWT 2.8
    logLevel = "INFO"
    
    /** Java args */
    maxHeapSize="1024m"
  }
  
  
}

```

**Comment by fdumay** [comment]
In the console. You can increase the log level with `gradle gwtCompile --info`or `gradle gwtCompile --debug`

And/Or on the gwt compiler.

```
putnami{
    compile {
        /** The level of logging detail (ERROR, WARN, INFO, TRACE, DEBUG, SPAM, ALL) */
        logLevel = "INFO"
    }
}
```

Anyway, the issue come from gwtp-all wich embed gwt:2.7. so to fix it you can exclude the transitive deps:

```
	compile('com.gwtplatform:gwtp-all:1.5.1') {
		exclude group: 'com.google.gwt'
	}
```

**Comment by confile** [comment]
@fdumay it works fine. Thanks for help. 

I used: ``googlePluginEclipse = true``: 

Here is a Sample class: 

![grails_-_majestella-gwt_src_main_java_majestella_widget_client_helper_postmessagehelper_java_-_groovy_grails_tool_suite_-__users_mg_documents_grails_ggts3_6_4-gwt](https://cloud.githubusercontent.com/assets/64265/13524112/95c64ae6-e1f9-11e5-8c5b-f2d716f51c38.jpg)

The expression is correct but still shows an error. It only deletes the error when I use the following expression: 

```
this.@majestella.widget.client.helper.PostMessageHelper::getParentDiv();
```

**Comment by fdumay** [comment]
Right, but this "error" comes from GPE.
The plugin seems to set properly the GPE nature. And provide the autocompletion to fix that issue.
Is it OK for you?

**Comment by confile** [comment]
Yes works great. Thanks. So the bug is in GPE?

**Comment by fdumay** [comment]
Bug or not featured??? I don't know.
Anyway, it compiles with `gwtCompile`, so I guess...

**Comment by confile** [comment]
@fdumay Where can I file a bug for that?

**Comment by fdumay** [comment]
Actually, i've no idea. You should talk to it with brandon.

**Comment by confile** [comment]
Could you please post the link to his profile?

**Comment by fdumay** [comment]
Brandon  donnelson @ Branflake2267

From what i know, he know what's up on gpe.

Fabien

**Comment by confile** [comment]
@branflake2267 Do you have any idea how to fix that problem on GPE?
