### ISSUE TITLE
gwtDev and RPC serialization

### ISSUE THREAD

**Issue by pablowatson** [Putnami/putnami-gradle-plugin#9]
Hi,

I have set up a somewhat large multi module project using your gradle plugin and everything works really nicely. I can build and run the gwt app perfectly. However, when I run the application in super dev mode via gwtDev none of the RPC serialization works (note all of the objects simply implement Serializable rather than the GWT IsSerializable).

I assume this is related ot this issue.

http://stackoverflow.com/questions/2122798/gwt-occasional-com-google-gwt-user-client-rpc-serializationexception

I am using Java 7 and GWT 2.7.

Any suggestions?

Cheers,
Paul

**Comment by fdumay** [comment]
Hi Paul,

Congrats for your switch on putnami-gradle-plugin ;)
Concerning you RPC serialization issue, I reckon that Serializable vs IsSerializable doesn't matter since a while. 
You may need to add to gwt-servlet lib : 
```
putnami{
    module '...'
    gwtServletLib = true;
}
```

If it doesn't solve the problem! Is your problem come from the client side or de server side? I'll maybe provide a better help with a stacktrace.

**Comment by pablowatson** [comment]
Hi Fabian,

I tried setting gwtServletLib = true, however this did not seem to make any difference. Just to confirm I am not being an idiot I set the gwtServletLib = true in the build.gradle file for the webapp module and I am running gradle gwtDev from the root folder.

For what is is worth here is the stack trace. As I said before this all works perfectly when you run using gwtRun.

```
com.google.gwt.user.client.rpc.SerializationException: Type 'com.arenasoft.bench.core.domain.User' was not assignable to 'com.google.gwt.user.client.rpc.IsSerializable' and did not have a custom field serializer.For security purposes, this type will not be serialized.: instance = PWatson
	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamWriter.serialize(ServerSerializationStreamWriter.java:667)
	at com.google.gwt.user.client.rpc.impl.AbstractSerializationStreamWriter.writeObject(AbstractSerializationStreamWriter.java:130)
	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamWriter$ValueWriter$8.write(ServerSerializationStreamWriter.java:153)
	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamWriter.serializeValue(ServerSerializationStreamWriter.java:587)
	at com.google.gwt.user.server.rpc.RPC.encodeResponse(RPC.java:631)
	at com.google.gwt.user.server.rpc.RPC.encodeResponseForSuccess(RPC.java:497)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:589)
	at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:571)
	at org.spring4gwt.server.SpringGwtRemoteServiceServlet.processCall(SpringGwtRemoteServiceServlet.java:37)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:373)
	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:800)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:245)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:744)
```

**Comment by fdumay** [comment]
I did reproduce your bug, I was because the launcherDir wasn't the same path as the war.

**Comment by fdumay** [comment]
You can test it with the lastest SNAPSHOT to use it : 

```
buildscript {
	repositories {
		mavenCentral()
		maven{ url 'https://oss.sonatype.org/content/repositories/snapshots/' }
	}
	dependencies {
		classpath 'fr.putnami.gwt:putnami-gradle-plugin:0.2.0-SNAPSHOT'
	}
}

apply plugin: 'fr.putnami.gwt'
	
repositories {
	mavenCentral()
	maven{ url 'https://oss.sonatype.org/content/repositories/snapshots/' }
}

putnami{
	module '...'
	gwtServletLib = true
}
```

You can refresh the dependecies with `gradle build --refresh-dependencies`

Please let me know how does it work.

**Comment by pablowatson** [comment]
Hi Fabien,

Thanks for looking in to this so quickly. I updated to the latest snapshot and refreshed the dependencies. I can still build and gwtRun, however when I do gwtDev I get the following error.

Thanks,
Paul


```
Super Dev Mode starting up
   Loading inherited module 'com.arenasoft.bench.gwt.webapp.App'
      [ERROR] Unable to find 'com/arenasoft/bench/gwt/webapp/App.gwt.xml' on your classpath; could be a typo, or maybe you forgot to include a classpath entry for source?
```

**Comment by fdumay** [comment]
Hi @pablowatson!

Please ca you retry, with the lastest SNAPSHOT? if it doesn't work, where is com/arenasoft/bench/gwt/webapp/App.gwt.xml  file? 
in the current project?
 in a other one? 
maybe in a external lib?

**Comment by pablowatson** [comment]
Hi Fabien,

I think I have figured out what is going on. I have my gwt.xml files and other stuff (css, supersource code etc.) in a resources folder with a package structure that matches that of the java directory e.g.

```
/ build.gradle
/ src
  |-- main
    |-- java
        |--com.arenasoft.bench.gwt.webapp
    |-- resources
        |--com.arenasoft.bench.gwt.webapp <-- App.gwt.xml is in here
    |-- webapp
  |-- test
    |-- java
    |-- resources
```
I don't think anything in the resources folder is being included when running gradle gwtDev. If I copy the App.gwt.xml  file to the appropriate package in the java directory getDev runs. Everything runs fine with gwtRun so I assume the resources folder is included in the full compile and build, but it does not seem to be included in gwtDev.

Hope this makes sense.

Paul

**Comment by fdumay** [comment]
Sorry, I didn't notify you earlier, but all classpath troubles are fixed.

**Comment by pablowatson** [comment]
Hi Fabien,

Certainly looks that way. I did a ```gradle build --refresh-dependencies``` and everything looks good with gwtDev.

Nice work.
Cheers,
Paul
